# Generated by Django 5.1.6 on 2026-04-10 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('post', 'Post Donation'), ('creator', 'Creator Donation'), ('event', 'Event Donation')], default='post', max_length=20, verbose_name='Donation Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100000.0)], verbose_name='Amount')),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='KES', max_length=3, verbose_name='Currency')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Donation Message')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Donate Anonymously')),
                ('phone_number', models.CharField(blank=True, help_text='Format: 254712345678 (without +)', max_length=15, null=True, verbose_name='Phone Number')),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='M-Pesa Receipt Number')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction ID')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Checkout Request ID')),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Merchant Request ID')),
                ('result_code', models.IntegerField(blank=True, null=True, verbose_name='Result Code')),
                ('result_description', models.TextField(blank=True, null=True, verbose_name='Result Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='Payment Status')),
                ('channel', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal')], default='mpesa', max_length=20, verbose_name='Payment Channel')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL, verbose_name='Donor')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='posts.post', verbose_name='Post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly'), ('all', 'All Time')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('unique_donors', models.PositiveIntegerField(default=0)),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_donation_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_stats', to='posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Stats',
                'verbose_name_plural': 'Donation Stats',
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stk_push', 'STK Push'), ('stk_push_query', 'STK Push Query'), ('b2c', 'B2C'), ('c2b', 'C2B')], max_length=20, verbose_name='Transaction Type')),
                ('request_data', models.JSONField(default=dict, verbose_name='Request Data')),
                ('response_data', models.JSONField(default=dict, verbose_name='Response Data')),
                ('callback_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Callback Data')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, verbose_name='Checkout Request ID')),
                ('merchant_request_id', models.CharField(db_index=True, max_length=100, verbose_name='Merchant Request ID')),
                ('result_code', models.IntegerField(blank=True, null=True, verbose_name='Result Code')),
                ('result_description', models.TextField(blank=True, null=True, verbose_name='Result Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='payments.donation')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', '-created_at'], name='payments_do_donor_i_681a56_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['recipient', '-created_at'], name='payments_do_recipie_11c0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', '-created_at'], name='payments_do_status_c454b2_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['mpesa_receipt_number'], name='payments_do_mpesa_r_250d21_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['transaction_id'], name='payments_do_transac_29649e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['checkout_request_id'], name='payments_do_checkou_764f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='payments_do_created_78f741_idx'),
        ),
        migrations.AddIndex(
            model_name='donationstats',
            index=models.Index(fields=['user', 'period', '-date'], name='payments_do_user_id_df7721_idx'),
        ),
        migrations.AddIndex(
            model_name='donationstats',
            index=models.Index(fields=['post', 'period', '-date'], name='payments_do_post_id_dbd5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='donationstats',
            index=models.Index(fields=['date'], name='payments_do_date_388a54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='donationstats',
            unique_together={('post', 'period', 'date'), ('user', 'period', 'date')},
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['merchant_request_id'], name='payments_mp_merchan_da2348_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['created_at'], name='payments_mp_created_78d6d8_idx'),
        ),
    ]
